"""api_v2.py -- the six endpoints behind the four screens (NORTH_STAR §7), plus /app.

Mounted on the existing FastAPI app by register(app) from backend.py. Thin: every
endpoint returns what a module computed (feed_build, story_read, big_moves, ledger);
nothing is recomputed here and nothing is invented. Shapes are the data contract
the front end (src/app.html) renders.

  GET  /app                    the four-screen front end
  GET  /big_moves              the Big Moves page (generated by big_moves_page.py)
  GET  /api/market_state       data/market_state.json
  GET  /api/feed               data/feed.json
  GET  /api/story?id=<event>   Story object for a corpus event (point-in-time)
  POST /api/story {text|url}   Story object for a live input (logs its claims)
  GET  /api/big_moves?asset=   episodes + rates for one asset
  GET  /api/ledger             the three scoreboards + recent claims
  POST /api/ledger/resolve     resolve every claim past its horizon, from data
  GET  /api/events?q=          corpus search for the Story door
  POST /api/rebuild            regenerate feed + market state (what the daily loop does)
"""
import json
import sqlite3
import subprocess
import sys
from pathlib import Path

from fastapi import HTTPException
from fastapi.responses import FileResponse, HTMLResponse
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
SRC = ROOT / "src"
DB = DATA / "oil.db"
sys.path.insert(0, str(SRC))


class StoryIn(BaseModel):
    text: str | None = None
    url: str | None = None
    knowable: str | None = None


class ChallengeIn(BaseModel):
    story_id: str
    conditions: dict[str, str] | None = None
    note: str | None = None


_CORPUS = {"mtime": None, "obj": None}


def _corpus():
    """The engine corpus (state vectors, prices, edges, IES-90), loaded once per DB mtime (~1 s)."""
    import engine.read as R
    from _db import connect
    m = DB.stat().st_mtime if DB.exists() else None
    if _CORPUS["obj"] is None or _CORPUS["mtime"] != m:
        _CORPUS["obj"] = R.Corpus.from_db(connect(read_only=True)); _CORPUS["mtime"] = m
    return _CORPUS["obj"]


def _walk_rows(name):
    """Live rows keyed by event_id (last row wins, as the walk writes them)."""
    p = DATA / "walk_forward" / name
    if not p.exists():
        return {}
    out = {}
    for line in open(p, encoding="utf-8"):
        if line.strip():
            r = json.loads(line); out[r["event_id"]] = r
    return out


# --- sealed reads survive archiving -------------------------------------------------------------------
# The walk archives every prior run into data/walk_forward/runs/<run_id>/*.jsonl.gz (protocol Amendment D),
# so a hash this project has published stops resolving the moment the next run archives it. Every citation
# in the paper would rot. These helpers look in the live files first and then in the archives, and the
# response always names the run that served it. (2026-09-03: the three demo hashes from walk_20260902T182828Z
# were unreachable through /api/walk/read while docs/demos/ quoted them.)
RUNS_DIR = DATA / "walk_forward" / "runs"


def _archived_runs():
    """Archived run ids, newest first."""
    if not RUNS_DIR.is_dir():
        return []
    return sorted((d.name for d in RUNS_DIR.iterdir() if d.is_dir()), reverse=True)


def _iter_jsonl(path):
    import gzip
    op = gzip.open if str(path).endswith(".gz") else open
    try:
        with op(path, "rt", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    yield json.loads(line)
    except (OSError, ValueError):
        return


_HEX = __import__("re").compile(r"^[0-9a-f]{8,64}$")


def _find_in(path, ident):
    """The row in `path` matching `ident`: an exact hash, a hash PREFIX (>= 8 hex chars -- the demo pages and the
    paper cite 12), or an event_id. Last match wins, as the live files do. Raises on an ambiguous prefix rather than
    guessing which read was meant."""
    exact = prefix = by_event = None
    seen = set()
    is_prefix = bool(_HEX.match(ident or ""))
    for r in _iter_jsonl(path):
        h = r.get("hash") or ""
        if h == ident:
            exact = r
        elif is_prefix and h.startswith(ident):
            prefix = r
            seen.add(h)
        if r.get("event_id") == ident:
            by_event = r
    if exact is not None:
        return exact
    if prefix is not None:
        if len(seen) > 1:
            raise HTTPException(409, f"'{ident}' is an ambiguous hash prefix: it matches {len(seen)} reads ({sorted(seen)[:4]}). Use more characters.")
        return prefix
    return by_event


def resolve_read(ident):
    """A sealed read by hash OR event_id: live files first, then the archives, newest first.
    Returns (read, score, served_from) or (None, None, None). served_from names the run and where it came from."""
    live = DATA / "walk_forward"
    r = _find_in(live / "reads.jsonl", ident)
    if r is not None:
        sc = None
        for x in _iter_jsonl(live / "scores.jsonl"):
            if x.get("read_hash") == r.get("hash") or (sc is None and x.get("event_id") == r.get("event_id")):
                if x.get("read_hash") == r.get("hash"):
                    sc = x
                    break
                sc = x
        return r, (sc or {}), {"run_id": r.get("run_id"), "source": "live", "path": "data/walk_forward/reads.jsonl"}
    for run in _archived_runs():
        d = RUNS_DIR / run
        r = _find_in(d / "reads.jsonl.gz", ident)
        if r is None:
            continue
        sc = None
        for x in _iter_jsonl(d / "scores.jsonl.gz"):
            if x.get("read_hash") == r.get("hash"):
                sc = x
                break
        return r, (sc or {}), {"run_id": r.get("run_id") or run, "source": "archived",
                               "path": f"data/walk_forward/runs/{run}/reads.jsonl.gz",
                               "note": "this run has been archived; the read is served from the archive so published hashes keep resolving"}
    return None, None, None


def _json(p, default=None):
    try:
        return json.load(open(p))
    except Exception:
        return default if default is not None else {}


def _pending_detail(rows, resolved):
    """Split "pending" into the claims that can still resolve and the ones that never will.

    DESIGN.md §3.3 wants the Ledger to lead with the checkable and to show a HORIZON where a
    scoreboard is empty. Both need a pending count that means something. `ledger.scoreboards()`
    counts pending as "checkable and not yet resolved", but `ledger.resolve()` skips
    `modality == 'hypothetical'` unconditionally -- a claim like "Iran WILL retaliate IF ..." is
    checkable in form and unresolvable in fact. Those claims sit in the count for ever, so a
    screen that prints the raw number tells the reader a resolution is coming that never is.

    So the two are separated here and named on the screen. This computes no verdict and resolves
    nothing; it reports which bucket each unresolved claim is in and why. ledger.py is shared with
    session H and is not edited from here -- the defect in its `counts.pending` is written up in
    data/handoffs/A_to_H_2026-09-03_pending_count.md.
    """
    open_claims = [c for c in rows if c.get("checkable") and c["claim_id"] not in resolved]
    hypo = [c for c in open_claims if c.get("modality") == "hypothetical"]
    awaiting = [c for c in open_claims if c.get("modality") != "hypothetical"]
    return {
        "open": len(open_claims),
        "awaiting_horizon": len(awaiting),
        "never_resolves": len(hypo),
        "never_resolves_why": ("logged as hypothetical (a conditional or a forecast attributed to someone else); "
                               "ledger.resolve() skips this modality, so these are recorded, not pending"),
        "next_due": _next_due(awaiting),
        "source": "data/ledger/claims.jsonl + data/ledger/resolutions.jsonl",
    }


def _next_due(awaiting):
    """The soonest horizon among claims that can still resolve, or a stated reason there is none.

    A calendar-unit claim has an exact due date: knowable + horizon_days. A trading-unit claim does
    NOT -- `ledger.resolve()` waits for the price series to carry `horizon_days` more observations,
    and nobody knows today which calendar date the 20th future trading day lands on. It is reported
    in the unit it is actually measured in (trading days observed, out of the horizon) rather than
    converted to a calendar date by a fudge factor, which would be a number with no source
    (charter section 2 rule 1, DESIGN.md section 6).
    """
    from datetime import date, timedelta
    cal, trade = [], []
    for c in awaiting:
        k = (c.get("knowable") or c.get("logged_at") or "")[:10]
        h = c.get("horizon_days")
        if not k or h is None:
            continue
        if c.get("horizon_unit") == "calendar":
            try:
                cal.append((str(date.fromisoformat(k) + timedelta(days=int(h))), c["claim_id"]))
            except ValueError:
                continue
        else:
            trade.append((k, h, c))
    if cal:
        due, cid = min(cal)
        return {"date": due, "claim_id": cid, "basis": "calendar days from the knowable date, exact"}
    if not trade:
        return {"date": None, "note": "no claim is awaiting a horizon"}
    # Trading-unit: say how far along the soonest claim is, measured against the series itself.
    import ledger as L
    import pandas as pd
    conn = sqlite3.connect(DB)
    try:
        best = None
        for k, h, c in trade:
            try:
                s = L._price(conn, c.get("series") or "fred.DCOILBRENTEU")
                pos = s.index.searchsorted(pd.Timestamp(k))
                seen = max(0, len(s) - 1 - int(pos))
                last = str(s.index[-1].date()) if len(s) else None
            except Exception:
                continue
            row = {"date": None, "claim_id": c["claim_id"], "horizon_days": h, "horizon_unit": "trading",
                   "observed": min(seen, h), "series": c.get("series") or "fred.DCOILBRENTEU",
                   "series_last_obs": last,
                   "basis": (f"{min(seen, h)} of {h} trading days observed since {k}; the due date is the "
                             f"date of the {h}th trading observation, which is not knowable in advance. "
                             f"{c.get('series') or 'fred.DCOILBRENTEU'} ends {last}.")}
            if best is None or row["observed"] > best["observed"]:
                best = row
        return best or {"date": None, "note": "no price series available for the awaiting claims"}
    finally:
        conn.close()


def register(app):
    @app.get("/app", response_class=HTMLResponse)
    def app_page():
        return HTMLResponse((SRC / "app.html").read_text(encoding="utf-8"))

    @app.get("/big_moves", response_class=HTMLResponse)
    def big_moves_page():
        p = SRC / "big_moves.html"
        if not p.exists():
            subprocess.run([sys.executable, str(SRC / "big_moves_page.py")], check=False)
        return HTMLResponse(p.read_text(encoding="utf-8"))

    @app.get("/api/market_state")
    def api_market_state():
        return _json(DATA / "market_state.json", {"assets": [], "note": "run python3 src/feed_build.py"})

    @app.get("/api/feed")
    def api_feed():
        return _json(DATA / "feed.json", {"material": [], "in_line": [], "noise": [], "counts": {}, "note": "run python3 src/feed_build.py"})

    @app.get("/api/story")
    def api_story_get(id: str):
        import story_read as SR
        s = SR.read(event_id=id, log=False)
        if "error" in s:
            raise HTTPException(404, s["error"])
        return s

    @app.post("/api/story")
    def api_story_post(body: StoryIn):
        import story_read as SR
        arg = (body.url or body.text or "").strip()
        if not arg:
            raise HTTPException(400, "paste a headline, paragraph, or URL")
        return SR.read(arg=arg, knowable=body.knowable, log=True)

    @app.get("/api/big_moves")
    def api_big_moves(asset: str = "brent"):
        p = DATA / "big_moves" / f"{asset}.json"
        if not p.exists():
            raise HTTPException(404, f"no big-moves file for {asset}; run python3 src/big_moves.py")
        return _json(p)

    @app.get("/api/ledger")
    def api_ledger(limit: int = 40):
        import ledger as L
        conn = sqlite3.connect(DB)
        try:
            boards = L.scoreboards(conn)
        finally:
            conn.close()
        rows = L._rows(L.CLAIMS)
        res = {r["claim_id"]: r for r in L._rows(L.RESOLUTIONS)}
        recent = []
        for r in rows[-limit:][::-1]:
            recent.append({**{k: r.get(k) for k in ("claim_id", "story_id", "source", "logged_at", "knowable", "text", "kind",
                                                     "asset", "direction", "level", "horizon_days", "horizon_unit", "checkable",
                                                     "verdict", "r", "n", "modality")},
                           "resolution": res.get(r["claim_id"])})
        rp = DATA / "reader_eval" / "score.json"                 # Brief A-9: the desk measures its own reading
        reval = _json(rp) or {"label": "reader accuracy (unaudited gold)", "note": "not run: python3 src/reader_eval.py"}
        return {**boards, "recent": recent, "pending_detail": _pending_detail(rows, res),
                "reader_eval": {k: reval.get(k) for k in ("label", "class_accuracy", "class_correct", "n", "entity_f1", "reader_modes",
                                                                                    "model", "gold_status", "generated_at", "threshold_class", "note")}}

    @app.post("/api/ledger/resolve")
    def api_ledger_resolve():
        import ledger as L
        conn = sqlite3.connect(DB)
        try:
            n = L.resolve(conn)
        finally:
            conn.close()
        return {"newly_resolved": n}

    @app.get("/api/events")
    def api_events(q: str = "", limit: int = 30):
        conn = sqlite3.connect(DB)
        like = f"%{q.strip()}%"
        rows = conn.execute(
            "SELECT DISTINCT e.event_id, e.event_date, e.type, e.title FROM events e "
            "LEFT JOIN event_entities ee ON ee.event_id=e.event_id "
            "WHERE e.title LIKE ? OR e.event_id LIKE ? OR e.type LIKE ? OR e.event_date LIKE ? OR ee.entity_id LIKE ? "
            "ORDER BY e.event_date DESC LIMIT ?", (like, like, like, like, like, limit)).fetchall()
        conn.close()
        return [{"event_id": r[0], "date": r[1], "type": r[2], "title": r[3]} for r in rows]

    @app.get("/api/challenge/vocab")
    def api_challenge_vocab():
        import challenge as C
        conn = sqlite3.connect(DB)
        try:
            return {**C.vocab(conn), "fields_order": list(C.FIELDS), "registration": C.REGISTRATION}
        finally:
            conn.close()

    @app.post("/api/challenge")
    def api_challenge(body: ChallengeIn):
        """Re-read Layer G under the analyst's conditions (Amendment 4). Every challenge is logged,
        refused ones included; a refusal returns 400 with the reasons and the vocabulary."""
        import challenge as C
        conn = sqlite3.connect(DB)
        try:
            r = C.run(conn, body.story_id, body.conditions or {}, note=body.note or "")
        finally:
            conn.close()
        if r.get("status") == "REFUSED":
            raise HTTPException(400, {"errors": r["errors"], "challenge_id": r["challenge_id"], "vocab": r.get("vocab", {}).get("fields")})
        return r

    @app.get("/api/challenges")
    def api_challenges(story_id: str = "", limit: int = 40):
        import challenge as C
        rs = [r for r in C.rows() if not story_id or r.get("story_id") == story_id]
        return rs[-limit:][::-1]

    @app.get("/api/engine_read")
    def api_engine_read(id: str, as_of: str | None = None, weighting: str | None = None):
        """The state-vector read for a corpus event, point-in-time (engine.read; PATH Step 7)."""
        import engine.read as R
        import engine.similarity as S
        c = _corpus()
        if id not in c.by_id:
            raise HTTPException(404, f"unknown event {id}")
        menu = S.load_menu()["items"]
        w = next((m for m in menu if m["id"] == weighting), menu[0])
        r = R.read(c, c.by_id[id], as_of=as_of, weighting=w)
        r["weighting_note"] = f"menu item {w['id']} (registered menu; the walk's Hedge weights are in data/walk_forward/weights.jsonl)"
        return r

    @app.get("/api/walk/summary")
    def api_walk_summary():
        s = _json(DATA / "walk_forward" / "summary.json")
        if not s:
            raise HTTPException(404, "no walk summary; run python3 src/walk.py")
        # Brief A-1 (2026-09-02): pass the published summary through WHOLE -- no key whitelist, so the endpoint can never
        # drift from summary.json again (the earlier list read `leakage` / `rps_vs`, which the file never had). The only
        # thing dropped is each tier task's per-item table (`items_vs_climatology`), which is large; /api/walk/read has it.
        tiers = {}
        for t, d in (s.get("tiers") or {}).items():
            td = dict(d)
            for task in ("G", "P", "M"):
                if isinstance(td.get(task), dict) and "items_vs_climatology" in td[task]:
                    td[task] = {k: v for k, v in td[task].items() if k != "items_vs_climatology"}
            tiers[t] = td
        return {k: v for k, v in s.items() if k != "tiers"} | {"tiers": tiers}

    @app.get("/api/record")
    def api_record():
        """NORTH_STAR §7 Record bar (Brief A-14): n events, n sealed reads, the §7 verdict statuses verbatim, last run_id, audit status."""
        import audit_ies90 as AU
        conn = sqlite3.connect(DB)
        try:
            n_events = conn.execute("SELECT COUNT(*) FROM events").fetchone()[0]
            n_geo = conn.execute("SELECT COUNT(*) FROM events WHERE type IN ('conflict_escalation','infrastructure_attack','chokepoint_disruption','sanctions')").fetchone()[0]
            n_ies = conn.execute("SELECT COUNT(*) FROM event_outcomes WHERE source='ies90' AND field='level'").fetchone()[0]
        finally:
            conn.close()
        s = _json(DATA / "walk_forward" / "summary.json") or {}
        reads = _walk_rows("reads.jsonl")
        rules = (s.get("verdict") or {}).get("rules") or {}
        au = AU.status()
        return {"n_events": n_events, "n_geopolitical": n_geo, "n_ies90_labels": n_ies, "n_reads": len(reads),
                "run_id": s.get("run_id"), "generated_at": s.get("generated_at"),
                "statuses": {"engine:G": (rules.get("engine:G") or {}).get("status"), "engine:P": (rules.get("engine:P") or {}).get("status")},
                "audit": {"status": au.get("status"), "n_done": au.get("n_done"), "n_rows": au.get("n_rows"), "kappa": au.get("kappa"), "passed": au.get("passed")},
                "label": "the record: corpus, sealed reads, protocol §7 statuses verbatim, label audit"}

    @app.get("/api/walk/audit")
    def api_walk_audit():
        """The IES-90 label audit as recorded by Joe (data/audits/outcome_audit.json, written only by src/audit_ies90.py). Read-only."""
        import audit_ies90 as AU
        return AU.status()

    @app.get("/api/walk/list")
    def api_walk_list(run: str | None = None):
        """The live run's reads by default; `?run=<run_id>` lists an archived run. Every row names the run it came
        from, so a row cited from the desk can be found again after that run is archived."""
        if run and run in _archived_runs():
            d = RUNS_DIR / run
            reads = {}
            for x in _iter_jsonl(d / "reads.jsonl.gz"):
                reads[x["event_id"]] = x
            scores = {}
            for x in _iter_jsonl(d / "scores.jsonl.gz"):
                scores[x["event_id"]] = x
            source = "archived"
        elif run:
            raise HTTPException(404, f"no archived run {run}; archived: {_archived_runs()}")
        else:
            reads, scores = _walk_rows("reads.jsonl"), _walk_rows("scores.jsonl")
            source = "live"
        out = []
        for eid, r in reads.items():
            sc = scores.get(eid) or {}
            e = (sc.get("scores") or {}).get("engine") or {}; cl = (sc.get("scores") or {}).get("climatology") or {}
            out.append({"event_id": eid, "date": r.get("date"), "type": r.get("type"), "tier": r.get("tier"),
                        "burn_in_ok": r.get("burn_in_ok"), "n_pool": r.get("n_pool"),
                        "outcome": sc.get("outcome"), "G_brier": (e.get("G") or {}).get("brier"), "G_clim": (cl.get("G") or {}).get("brier"),
                        "P_crps": (e.get("P") or {}).get("crps"), "P_clim": (cl.get("P") or {}).get("crps"),
                        "sealed_at": r.get("sealed_at"), "hash": r.get("hash"),
                        "run_id": r.get("run_id"), "source": source})
        out.sort(key=lambda x: x["date"] or "")
        return out

    @app.get("/api/walk/read")
    def api_walk_read(id: str):
        """One sealed read + its score + the outcome, exactly as the walk wrote them. `id` is an event_id OR a read
        hash; the live files are searched first, then the archived runs, so a hash this project has published keeps
        resolving after its run is archived. The reply names the run that served it."""
        r, sc, served = resolve_read(id)
        if not r:
            raise HTTPException(404, f"no sealed read for {id} in the live files or any archived run")
        c = _corpus()
        ev = c.by_id.get(r.get("event_id")) or {}
        return {"read": r, "score": sc, "served_from": served,
                "event": {k: ev.get(k) for k in ("event_id", "event_date", "type", "title", "source_url")},
                "titles": {a: (c.by_id.get(a) or {}).get("title") for a in ((r.get("engine") or {}).get("G_atoms") or {}).get("ids", [])}}

    @app.post("/api/rebuild")
    def api_rebuild():
        import feed_build as FB
        ms, fd = FB.run()
        return {"market_state_assets": len(ms["assets"]), "feed": fd["counts"], "day": fd["day"]}
