"""api_v2.py -- the six endpoints behind the four screens (NORTH_STAR §7), plus /app.

Mounted on the existing FastAPI app by register(app) from backend.py. Thin: every
endpoint returns what a module computed (feed_build, story_read, big_moves, ledger);
nothing is recomputed here and nothing is invented. Shapes are the data contract
the front end (src/app.html) renders.

  GET  /app                    the four-screen front end
  GET  /big_moves              the Big Moves page (generated by big_moves_page.py)
  GET  /api/market_state       data/market_state.json
  GET  /api/feed               data/feed.json
  GET  /api/story?id=<event>   Story object for a corpus event (point-in-time)
  POST /api/story {text|url}   Story object for a live input (logs its claims)
  GET  /api/big_moves?asset=   episodes + rates for one asset
  GET  /api/ledger             the three scoreboards + recent claims
  POST /api/ledger/resolve     resolve every claim past its horizon, from data
  GET  /api/events?q=          corpus search for the Story door
  POST /api/rebuild            regenerate feed + market state (what the daily loop does)
"""
import json
import sqlite3
import subprocess
import sys
from pathlib import Path

from fastapi import HTTPException
from fastapi.responses import FileResponse, HTMLResponse
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
SRC = ROOT / "src"
DB = DATA / "oil.db"
sys.path.insert(0, str(SRC))


class StoryIn(BaseModel):
    text: str | None = None
    url: str | None = None
    knowable: str | None = None


class ChallengeIn(BaseModel):
    story_id: str
    conditions: dict[str, str] | None = None
    note: str | None = None


_CORPUS = {"mtime": None, "obj": None}


def _corpus():
    """The engine corpus (state vectors, prices, edges, IES-90), loaded once per DB mtime (~1 s)."""
    import engine.read as R
    from _db import connect
    m = DB.stat().st_mtime if DB.exists() else None
    if _CORPUS["obj"] is None or _CORPUS["mtime"] != m:
        _CORPUS["obj"] = R.Corpus.from_db(connect(read_only=True)); _CORPUS["mtime"] = m
    return _CORPUS["obj"]


def _walk_rows(name):
    p = DATA / "walk_forward" / name
    if not p.exists():
        return {}
    out = {}
    for line in open(p, encoding="utf-8"):
        if line.strip():
            r = json.loads(line); out[r["event_id"]] = r
    return out


def _json(p, default=None):
    try:
        return json.load(open(p))
    except Exception:
        return default if default is not None else {}


def register(app):
    @app.get("/app", response_class=HTMLResponse)
    def app_page():
        return HTMLResponse((SRC / "app.html").read_text(encoding="utf-8"))

    @app.get("/big_moves", response_class=HTMLResponse)
    def big_moves_page():
        p = SRC / "big_moves.html"
        if not p.exists():
            subprocess.run([sys.executable, str(SRC / "big_moves_page.py")], check=False)
        return HTMLResponse(p.read_text(encoding="utf-8"))

    @app.get("/api/market_state")
    def api_market_state():
        return _json(DATA / "market_state.json", {"assets": [], "note": "run python3 src/feed_build.py"})

    @app.get("/api/feed")
    def api_feed():
        return _json(DATA / "feed.json", {"material": [], "in_line": [], "noise": [], "counts": {}, "note": "run python3 src/feed_build.py"})

    @app.get("/api/story")
    def api_story_get(id: str):
        import story_read as SR
        s = SR.read(event_id=id, log=False)
        if "error" in s:
            raise HTTPException(404, s["error"])
        return s

    @app.post("/api/story")
    def api_story_post(body: StoryIn):
        import story_read as SR
        arg = (body.url or body.text or "").strip()
        if not arg:
            raise HTTPException(400, "paste a headline, paragraph, or URL")
        return SR.read(arg=arg, knowable=body.knowable, log=True)

    @app.get("/api/big_moves")
    def api_big_moves(asset: str = "brent"):
        p = DATA / "big_moves" / f"{asset}.json"
        if not p.exists():
            raise HTTPException(404, f"no big-moves file for {asset}; run python3 src/big_moves.py")
        return _json(p)

    @app.get("/api/ledger")
    def api_ledger(limit: int = 40):
        import ledger as L
        conn = sqlite3.connect(DB)
        try:
            boards = L.scoreboards(conn)
        finally:
            conn.close()
        rows = L._rows(L.CLAIMS)
        res = {r["claim_id"]: r for r in L._rows(L.RESOLUTIONS)}
        recent = []
        for r in rows[-limit:][::-1]:
            recent.append({**{k: r.get(k) for k in ("claim_id", "story_id", "source", "logged_at", "knowable", "text", "kind",
                                                     "asset", "direction", "level", "horizon_days", "horizon_unit", "checkable",
                                                     "verdict", "r", "n", "modality")},
                           "resolution": res.get(r["claim_id"])})
        return {**boards, "recent": recent}

    @app.post("/api/ledger/resolve")
    def api_ledger_resolve():
        import ledger as L
        conn = sqlite3.connect(DB)
        try:
            n = L.resolve(conn)
        finally:
            conn.close()
        return {"newly_resolved": n}

    @app.get("/api/events")
    def api_events(q: str = "", limit: int = 30):
        conn = sqlite3.connect(DB)
        like = f"%{q.strip()}%"
        rows = conn.execute(
            "SELECT DISTINCT e.event_id, e.event_date, e.type, e.title FROM events e "
            "LEFT JOIN event_entities ee ON ee.event_id=e.event_id "
            "WHERE e.title LIKE ? OR e.event_id LIKE ? OR e.type LIKE ? OR e.event_date LIKE ? OR ee.entity_id LIKE ? "
            "ORDER BY e.event_date DESC LIMIT ?", (like, like, like, like, like, limit)).fetchall()
        conn.close()
        return [{"event_id": r[0], "date": r[1], "type": r[2], "title": r[3]} for r in rows]

    @app.get("/api/challenge/vocab")
    def api_challenge_vocab():
        import challenge as C
        conn = sqlite3.connect(DB)
        try:
            return {**C.vocab(conn), "fields_order": list(C.FIELDS), "registration": C.REGISTRATION}
        finally:
            conn.close()

    @app.post("/api/challenge")
    def api_challenge(body: ChallengeIn):
        """Re-read Layer G under the analyst's conditions (Amendment 4). Every challenge is logged,
        refused ones included; a refusal returns 400 with the reasons and the vocabulary."""
        import challenge as C
        conn = sqlite3.connect(DB)
        try:
            r = C.run(conn, body.story_id, body.conditions or {}, note=body.note or "")
        finally:
            conn.close()
        if r.get("status") == "REFUSED":
            raise HTTPException(400, {"errors": r["errors"], "challenge_id": r["challenge_id"], "vocab": r.get("vocab", {}).get("fields")})
        return r

    @app.get("/api/challenges")
    def api_challenges(story_id: str = "", limit: int = 40):
        import challenge as C
        rs = [r for r in C.rows() if not story_id or r.get("story_id") == story_id]
        return rs[-limit:][::-1]

    @app.get("/api/engine_read")
    def api_engine_read(id: str, as_of: str | None = None, weighting: str | None = None):
        """The state-vector read for a corpus event, point-in-time (engine.read; PATH Step 7)."""
        import engine.read as R
        import engine.similarity as S
        c = _corpus()
        if id not in c.by_id:
            raise HTTPException(404, f"unknown event {id}")
        menu = S.load_menu()["items"]
        w = next((m for m in menu if m["id"] == weighting), menu[0])
        r = R.read(c, c.by_id[id], as_of=as_of, weighting=w)
        r["weighting_note"] = f"menu item {w['id']} (registered menu; the walk's Hedge weights are in data/walk_forward/weights.jsonl)"
        return r

    @app.get("/api/walk/summary")
    def api_walk_summary():
        s = _json(DATA / "walk_forward" / "summary.json")
        if not s:
            raise HTTPException(404, "no walk summary; run python3 src/walk.py")
        # Brief A-1 (2026-09-02): pass the published summary through WHOLE -- no key whitelist, so the endpoint can never
        # drift from summary.json again (the earlier list read `leakage` / `rps_vs`, which the file never had). The only
        # thing dropped is each tier task's per-item table (`items_vs_climatology`), which is large; /api/walk/read has it.
        tiers = {}
        for t, d in (s.get("tiers") or {}).items():
            td = dict(d)
            for task in ("G", "P", "M"):
                if isinstance(td.get(task), dict) and "items_vs_climatology" in td[task]:
                    td[task] = {k: v for k, v in td[task].items() if k != "items_vs_climatology"}
            tiers[t] = td
        return {k: v for k, v in s.items() if k != "tiers"} | {"tiers": tiers}

    @app.get("/api/walk/list")
    def api_walk_list():
        reads, scores = _walk_rows("reads.jsonl"), _walk_rows("scores.jsonl")
        out = []
        for eid, r in reads.items():
            sc = scores.get(eid) or {}
            e = (sc.get("scores") or {}).get("engine") or {}; cl = (sc.get("scores") or {}).get("climatology") or {}
            out.append({"event_id": eid, "date": r.get("date"), "type": r.get("type"), "tier": r.get("tier"),
                        "burn_in_ok": r.get("burn_in_ok"), "n_pool": r.get("n_pool"),
                        "outcome": sc.get("outcome"), "G_brier": (e.get("G") or {}).get("brier"), "G_clim": (cl.get("G") or {}).get("brier"),
                        "P_crps": (e.get("P") or {}).get("crps"), "P_clim": (cl.get("P") or {}).get("crps"),
                        "sealed_at": r.get("sealed_at"), "hash": r.get("hash")})
        out.sort(key=lambda x: x["date"] or "")
        return out

    @app.get("/api/walk/read")
    def api_walk_read(id: str):
        """One sealed read + its score + the outcome, exactly as the walk wrote them."""
        r = _walk_rows("reads.jsonl").get(id)
        if not r:
            raise HTTPException(404, f"no sealed read for {id}")
        sc = _walk_rows("scores.jsonl").get(id) or {}
        c = _corpus()
        ev = c.by_id.get(id) or {}
        return {"read": r, "score": sc, "event": {k: ev.get(k) for k in ("event_id", "event_date", "type", "title", "source_url")},
                "titles": {a: (c.by_id.get(a) or {}).get("title") for a in ((r.get("engine") or {}).get("G_atoms") or {}).get("ids", [])}}

    @app.post("/api/rebuild")
    def api_rebuild():
        import feed_build as FB
        ms, fd = FB.run()
        return {"market_state_assets": len(ms["assets"]), "feed": fd["counts"], "day": fd["day"]}
