"""api_v2.py -- the six endpoints behind the four screens (NORTH_STAR §7), plus /app.

Mounted on the existing FastAPI app by register(app) from backend.py. Thin: every
endpoint returns what a module computed (feed_build, story_read, big_moves, ledger);
nothing is recomputed here and nothing is invented. Shapes are the data contract
the front end (src/app.html) renders.

  GET  /app                    the four-screen front end
  GET  /big_moves              the Big Moves page (generated by big_moves_page.py)
  GET  /api/market_state       data/market_state.json
  GET  /api/feed               data/feed.json
  GET  /api/story?id=<event>   Story object for a corpus event (point-in-time)
  POST /api/story {text|url}   Story object for a live input (logs its claims)
  GET  /api/big_moves?asset=   episodes + rates for one asset
  GET  /api/ledger             the three scoreboards + recent claims
  POST /api/ledger/resolve     resolve every claim past its horizon, from data
  GET  /api/events?q=          corpus search for the Story door
  POST /api/rebuild            regenerate feed + market state (what the daily loop does)
"""
import json
import sqlite3
import subprocess
import sys
from pathlib import Path

from fastapi import HTTPException
from fastapi.responses import FileResponse, HTMLResponse
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
SRC = ROOT / "src"
DB = DATA / "oil.db"
sys.path.insert(0, str(SRC))


class StoryIn(BaseModel):
    text: str | None = None
    url: str | None = None
    knowable: str | None = None


def _json(p, default=None):
    try:
        return json.load(open(p))
    except Exception:
        return default if default is not None else {}


def register(app):
    @app.get("/app", response_class=HTMLResponse)
    def app_page():
        return HTMLResponse((SRC / "app.html").read_text(encoding="utf-8"))

    @app.get("/big_moves", response_class=HTMLResponse)
    def big_moves_page():
        p = SRC / "big_moves.html"
        if not p.exists():
            subprocess.run([sys.executable, str(SRC / "big_moves_page.py")], check=False)
        return HTMLResponse(p.read_text(encoding="utf-8"))

    @app.get("/api/market_state")
    def api_market_state():
        return _json(DATA / "market_state.json", {"assets": [], "note": "run python3 src/feed_build.py"})

    @app.get("/api/feed")
    def api_feed():
        return _json(DATA / "feed.json", {"material": [], "in_line": [], "noise": [], "counts": {}, "note": "run python3 src/feed_build.py"})

    @app.get("/api/story")
    def api_story_get(id: str):
        import story_read as SR
        s = SR.read(event_id=id, log=False)
        if "error" in s:
            raise HTTPException(404, s["error"])
        return s

    @app.post("/api/story")
    def api_story_post(body: StoryIn):
        import story_read as SR
        arg = (body.url or body.text or "").strip()
        if not arg:
            raise HTTPException(400, "paste a headline, paragraph, or URL")
        return SR.read(arg=arg, knowable=body.knowable, log=True)

    @app.get("/api/big_moves")
    def api_big_moves(asset: str = "brent"):
        p = DATA / "big_moves" / f"{asset}.json"
        if not p.exists():
            raise HTTPException(404, f"no big-moves file for {asset}; run python3 src/big_moves.py")
        return _json(p)

    @app.get("/api/ledger")
    def api_ledger(limit: int = 40):
        import ledger as L
        conn = sqlite3.connect(DB)
        try:
            boards = L.scoreboards(conn)
        finally:
            conn.close()
        rows = L._rows(L.CLAIMS)
        res = {r["claim_id"]: r for r in L._rows(L.RESOLUTIONS)}
        recent = []
        for r in rows[-limit:][::-1]:
            recent.append({**{k: r.get(k) for k in ("claim_id", "story_id", "source", "logged_at", "knowable", "text", "kind",
                                                     "asset", "direction", "level", "horizon_days", "horizon_unit", "checkable",
                                                     "verdict", "r", "n", "modality")},
                           "resolution": res.get(r["claim_id"])})
        return {**boards, "recent": recent}

    @app.post("/api/ledger/resolve")
    def api_ledger_resolve():
        import ledger as L
        conn = sqlite3.connect(DB)
        try:
            n = L.resolve(conn)
        finally:
            conn.close()
        return {"newly_resolved": n}

    @app.get("/api/events")
    def api_events(q: str = "", limit: int = 30):
        conn = sqlite3.connect(DB)
        like = f"%{q.strip()}%"
        rows = conn.execute(
            "SELECT DISTINCT e.event_id, e.event_date, e.type, e.title FROM events e "
            "LEFT JOIN event_entities ee ON ee.event_id=e.event_id "
            "WHERE e.title LIKE ? OR e.event_id LIKE ? OR e.type LIKE ? OR e.event_date LIKE ? OR ee.entity_id LIKE ? "
            "ORDER BY e.event_date DESC LIMIT ?", (like, like, like, like, like, limit)).fetchall()
        conn.close()
        return [{"event_id": r[0], "date": r[1], "type": r[2], "title": r[3]} for r in rows]

    @app.post("/api/rebuild")
    def api_rebuild():
        import feed_build as FB
        ms, fd = FB.run()
        return {"market_state_assets": len(ms["assets"]), "feed": fd["counts"], "day": fd["day"]}
